# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  runing_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: menjalankan test
        run: | 
          npm install
          npm test 
